### ISSUE TITLE
error: no match for ‘operator=’ (operand types are ‘juce::Colour’ and ‘const std::optional<juce::Colour>’)

### ISSUE THREAD

**Issue by 38github** [versustunez/VEQ#3]
OpenSUSE Tumbleweed amd64, GCC 15.1

```
[ 39%] Building CXX object Plugin/CMakeFiles/VEQ.dir/Source/PluginProcessor.cpp.o
/tmp/VEQ/Plugin/Source/PluginProcessor.cpp: In member function ‘virtual void VSTProcessor::updateTrackProperties(const juce::AudioProcessor::TrackProperties&)’:
/tmp/VEQ/Plugin/Source/PluginProcessor.cpp:101:43: error: no match for ‘operator=’ (operand types are ‘juce::Colour’ and ‘const std::optional<juce::Colour>’)
  101 |   instance->state.TrackColor = properties.colour;
      |                                           ^~~~~~
/tmp/VEQ/Plugin/Source/PluginProcessor.cpp:101:43: note: there is 1 candidate
In file included from /tmp/VEQ/build/_deps/juce-src/modules/juce_graphics/juce_graphics.h:123,
                 from /tmp/VEQ/build/_deps/juce-src/modules/juce_audio_devices/juce_audio_devices.h:71,
                 from /tmp/VEQ/Plugin/Source/JuceHeader.h:4,
                 from /tmp/VEQ/Plugin/Source/Core/Parameter/Parameter.h:4,
                 from /tmp/VEQ/Plugin/Source/Events/Event.h:2,
                 from /tmp/VEQ/Plugin/Source/Events/EventHandler.h:3,
                 from /tmp/VEQ/Plugin/Source/BandListener.h:3,
                 from /tmp/VEQ/Plugin/Source/PluginProcessor.h:3,
                 from /tmp/VEQ/Plugin/Source/PluginProcessor.cpp:1:

```

**Comment by 38github** [comment]
I solved it. I forked your repo and also JUCE. Uploaded JUCE 8.0.4 to my fork instead of master. Edited the CMakeList file in my VEQ fork to clone my JUCE repo (8.0.4) instead of JUCE's master. I managed to compile it on Debian 13 aarch64 and it works fine in REAPER 7.45.
